apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head>
        <title>
        Nginx-Blue
        </title>
      <body>
        <h1 style="background-color: blue;">
        Welcome to Nginx-Blue!
        </h1>
      </body>
    </html>
