apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  labels:
    app: nginx
data:
  index.html: |
    <html>
      <head>
        <title>
        Nginx
        </title>
      <body>
        <h1>
        Welcome to Nginx!
        </h1>
      </body>
    </html>