apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <head>
        <title>
        Nginx-Green
        </title>
      <body>
        <h1 style="background-color: green;">
        Welcome to Nginx-Green!
        </h1>
      </body>
    </html>
