apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx
  labels:
    app: nginx
data:
  index.html: |
    <html>
      <head>
        <title>
        Welcome Page
        </title>
      <body>
        <h1>
        Welcome to Kubernetes!
        </h1>
      </body>
    </html>
