apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: golang:1.21.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: go
        - name: ELASTIC_APM_SERVER_URL
          value: https://elastic-apm.minikube.local/
        - name: ELASTIC_APM_SECRET_TOKEN
          value: F1Ddpc39Xr58L06d46Tn3XNI
        - name: ELASTIC_APM_ENVIRONMENT
          value: dev
        - name: ELASTIC_APM_SERVER_CA_CERT_FILE
          value: /mnt/c/Users/wmgoz/develop/kubernetes/k8s-setup/elastic-apm-ca.crt
        - name: ELASTIC_APM_VERIFY_SERVER_CERT
          value: true
        volumeMounts:
        - name: setup-file
          mountPath: /go/setup.sh
          subPath: setup.sh
        - name: go-main-file
          mountPath: /go/app/main.go
          subPath: main.go
          readOnly: true
        command: ['sh', '/go/setup.sh']
      volumes:
        - name: go-main-file
          configMap:
            name: go-cm
            items:
            - key: "main.go"
              path: "main.go"
        - name: setup-file
          configMap:
            name: go-cm
            items:
            - key: "setup.sh"
              path: "setup.sh"
              mode: 0755
