apiVersion: v1
kind: Secret
metadata:
  name: apm-secret
  labels:
    app: go
type: Opaque
data:
  # Dummy CERT
  elastic-apm-ca.crt: |
    MIIDFzCCAf+gAwIBAgIRAP+K5ba0mQ76LOG55by4vbswDQYJKoZIhvcNAQELBQAwJTEjMCEGA1UEAxMaZWxhc3RpYy1hcG0ubWluaWt1YmUubG9jYWwwHhcNMjMwOTIxMTQxNzI2WhcNMjQwOTIwMTQxNzI2WjAlMSMwIQYDVQQDExplbGFzdGljLWFwbS5taW5pa3ViZS5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKQ8+H4ALk9XZrudgxtXW7ltVd0/h44fmpUO+5JRrNMO91Vl3xIlWrFfbFKpKQD5w9iKqh4JqaO5ntu+sKXDhnPGT55+3FdehXvd1ry74ZnIlg/jaLxhirPi2sIbNZjcexmVu8O98uBt8/6oxeUPHIHkhue4cT3f7nuhtA4afHwY8IuiMhghrNxVjmb6xxcdfaPa0EfcANY9APBflWLhanuAAU/tCq1479wMurmoP2YrkAanEgl83FbWveNptod1gch41Ss23MA0hBOonAW0gAyiBdk9u9s1TPqDtP/13MbmaX20XJ13vn1lD9GcFGn+YCAqnBYwwzr/7idkrQcQJJUCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOeV2Q3xsLSa/DX+kZVgW4aBk84HMA0GCSqGSIb3DQEBCwUAA4IBAQAgffbBibMDlZpbcxtVzQqF1QfNjEoPGion6r3GH04gllEezchq7P8Kmsh8zmsn1VBdqjvC1wPtKxjyHClvM7S5VKeBwMNpDdUJU9wjYx1WZcTgvWiLapVv3/AVklB9GZAyCviwVYedy1oAcmTns5jHM5UKpsxXuDRO/HGkXhAX1aQKJTkJeoXfnuZFhfvTKsv7v+liJarrANoaz27U+adkyLaC2V+AYzWrJP1gUTCoa7XJo4jsWZHMngFEG8kXx7g/sac1v8Pxei5KNGwaOdsjzCpW4nDgh6cPK3tT9l4cuFABlxa2MuqBqcgqoCVVWsvNK4T4LRQ/Tl5cH469qRxU
  elastic-apm-tls.crt: |
    MIIDbDCCAlSgAwIBAgIQSgax3uqTpckgipA0+891xTANBgkqhkiG9w0BAQsFADAl
    MSMwIQYDVQQDExplbGFzdGljLWFwbS5taW5pa3ViZS5sb2NhbDAeFw0yMzA5MjEx
    NDQwMDBaFw0yNDA5MjAxNDQwMDBaMFUxDjAMBgNVBAYTBUphcGFuMQ4wDAYDVQQH
    EwVUb2t5bzEOMAwGA1UEChMFTXlPcmcxIzAhBgNVBAMTGmVsYXN0aWMtYXBtLm1p
    bmlrdWJlLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6N9D
    6gFWefCx5Ay/n5e45idEu9aUrQPShGNDbiY1Mcm9yllE1AVCefoM2xDX0WlH94D9
    m42BcYL3I0rHVZDgFIBxjpwYIpZWhGaM04rmNkbyKxkqEDq2ElS6SE5zoJSftjkX
    cyn1B5sZ+jUbrPVO08UVbvyttVVkpYHAYwd2f2r01OTHh+aNod666FHue3Q2IMcK
    Z0vP8h6b9/m6oax/zQYuuVFO3v4tXjy9FbfneA7On7PcWabB5P70RN0vfvklKExw
    qrmxqOfRgwJHq7FbQjU/NVZe4zgqTg1am6NZturymathvcTKfFRcYQSdB87FWrIF
    fsKesi31gF4UbLYxowIDAQABo2gwZjAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/
    BAIwADAfBgNVHSMEGDAWgBTnldkN8bC0mvw1/pGVYFuGgZPOBzAlBgNVHREEHjAc
    ghplbGFzdGljLWFwbS5taW5pa3ViZS5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEA
    NzLFUO8NE9M96hqVYHc657eMP+20H5X3KP52Cj/W3MwXK2zbXRkUmmOQpH4VkRhp
    Qbdt/DgBC6Jfp9uyTTrscnfDT1sIoPhv96nxJfppHNc7tDsvc4CItJkT8VtgPgYw
    a3Q+ULWRV+giQYLIuXWE98gLxb3KXlQC8V4Vjls7Wxfn7z+3Iw5XoPNTtxXe3xr4
    AI049wlwEIIgO0xGSIfnCJSEc4tk3DdfOIO3k2WGtDDLSz1re/EFnUYmzXRlPj+x
    LKXEwP/Wqo4NeGwaS3pwPho2PzaBelui/7ktWu6tfRaG3G8J3ts7yhK3mfN0gkVU
    nhJYtcR6f7DdBzSAUXvgUg==
  elastic-apm-tls.key: |
    MIIEpAIBAAKCAQEA6N9D6gFWefCx5Ay/n5e45idEu9aUrQPShGNDbiY1Mcm9yllE
    1AVCefoM2xDX0WlH94D9m42BcYL3I0rHVZDgFIBxjpwYIpZWhGaM04rmNkbyKxkq
    EDq2ElS6SE5zoJSftjkXcyn1B5sZ+jUbrPVO08UVbvyttVVkpYHAYwd2f2r01OTH
    h+aNod666FHue3Q2IMcKZ0vP8h6b9/m6oax/zQYuuVFO3v4tXjy9FbfneA7On7Pc
    WabB5P70RN0vfvklKExwqrmxqOfRgwJHq7FbQjU/NVZe4zgqTg1am6NZturymath
    vcTKfFRcYQSdB87FWrIFfsKesi31gF4UbLYxowIDAQABAoIBAEJPwWETPHLAzYco
    8jAZ3jb7m6D5e6DA4+N6+KqXCrLAxeCnBuhxDvr470w6QZqKJkoeWxk+dEvEhWdx
    Vc3R0V1FLhDz9hNzR/Ov2A4tEV0HWtJW+hlg/pO9uMX6QQbLC6eyHjFXE0U1L3KG
    SPk5aVb4WiAep8BpLp3KkuQgLegeG8c4FRhKB/qqmAGqMK3Ke6qZEKMCNvstLACu
    t82pGjUJcdptvnmkiLWuIocXZstJV5BXKLbeUPHUzVurbcfiJKw9+ARyul1NwBmv
    fNo/KEb51LSBzzj/XllZPKV/AFCmcpUbZT0t5R7atkeuPGOpJKZNZZzfdDquj1wB
    7Y5w85ECgYEA9VPa/NgbUj7FNe/cLF5gtJFkiZiPI8LbHy1SvnF4HHUePt22sbt0
    7Dm940yQt5VV3FgI2MavMf6djpUvjJorw4N0c5gVye3WPZ+u6XLWtqhJt/Fkq0yV
    0/apQoLy2HW76QVKIKiWTZkqqe64kZuQLRQpRwpaOApc2c5NaSVcuwcCgYEA8wCy
    fObzeeAddfy8up+8Nsih6rwYvvx6gbtjZ6zU1Q+zYslda6BTeedNi+E3BNR7SY5x
    B0cKAFQLGLIqAjbAwOT6m8fzZuS901OR1MYzhs32q+odDZ7UR1oO0ysoiZmK9OY/
    XeHOkchqZtQ8BXiDulSbnuZ4PlncqG55V1lCAYUCgYBQyP1K16sfiTYNzd+V6Lo1
    m88clFVGdGsNuDIQLnNcA6EjGIWJv24AP/9ssxDQs2djuMWpBLw6XVrq0eunhDk3
    F7moOwOpzB0Ji+TgUQWtfntQDDiXRA/ujcIs+cwYRaTMVgaT/JAKG472CHtUz4JJ
    peL11s3guGDdBFdvcXM4zwKBgQCrCWKX5zaYIdaapTlxYdzn8m+E+L+yLaNMjMh6
    wHtNO6/XaEQI7N/UfalnOy2uiJ/+NfP4W1f+wyjMSRqoVEF3g7Og0ivP0FCL3dZX
    HOpHh9CHUFECtThUwF6O42G0+A2GMkmHmtf6ZEX/+oIEl76f981RGoan3DgjlR5z
    DLAYwQKBgQDlMy/9BwUxvhSSPRLKmsSorsEPOs/bz1Lsg4EjyuF/09UXwYed4c+F
    xqaD0GmR0TShVHuaY1rOy66z8j0AUq3Jxrkl6/lGoLqebSBqpWUFOqM/tqVJl92k
    n3WPD91cYiW2yoio87+Oz4EpB16Ess22y74dYAM9243f/q1Uu6JiLQ==