apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  elastic-apm-ca.crt: |
    MIIDDDCCAfSgAwIBAgIQCfiEq6/g0nqnZzdLaohNmjANBgkqhkiG9w0BAQsFADAg
    MR4wHAYDVQQDExVhcmdvY2QubWluaWt1YmUubG9jYWwwHhcNMjMwOTIxMTQxNzI1
    WhcNMjQwOTIwMTQxNzI1WjAgMR4wHAYDVQQDExVhcmdvY2QubWluaWt1YmUubG9j
    YWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCt0m3mVtYC/ruQsLPG
    naYVEd8iAdAYpiQfHNR66bfACLpD9uGegrsnFAIHb9ZjGpMGKjSqPR1W7DrwZJlh
    BmxCW1Bv7DG6g3TVkLq5jRykkqHekJJT2ofrLWguBI2yAoGzo7TXCoNMY47E/rsF
    CLzRYJ+E5GlrM8RnxrVrjx2AwDGvpY+4Ns970181MkTXUfF/XGfESY6AbgmjbEAM
    5QqjK8c68B6rvq65Am16ZQEsBFbxgd9ggXDV+WEwvhk4kKkvUSo3URwVL4AfMbIp
    6Jze3FnCDs2pqNymWt2JyW6d8tBFfqeORdKyjV+pLkmvu9He4KpOV6IFkJiDiu//
    4imtAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0G
    A1UdDgQWBBRgAx76SWDK/ODoSKWaQUNhrD6O1jANBgkqhkiG9w0BAQsFAAOCAQEA
    WQ7zVdC9MQQSvDT7AqNSESf5ehfRSbNoJqJU/5s4K302Ks7SxYPPXoGqullNFby0
    VtGS+dliI1Vgs7KGHphV3C8dYPKrZ20K0K+u5h5cvzdOP8pAtDxoaKLfCJNc0CBq
    FFGschL/D9tNUZwzvcnZa4FftSiXC2bm0bI3QpmMETD+Z8v8u+KKAxxZysO9VSen
    vitF1tDpZKRUjtcZuPzGffOqpsdUgzodgqt2TZfuoRMgbAOT1tq5FsLLqAY77wOB
    a7HyZYCZAFF8tF7VLD1wmCIawKzQFc3Mtnv6h331MmpCoy1TmCbRMI9OOFekgq0l
    z07ghFot5DXg9Jv/ZQyp0Q==