apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  labels:
    app: nginx
data:
  index.html: |
    <html>
      <head>
        <title>
        Nginx-Red
        </title>
      <body>
        <h1 style="background-color: red;">
        Welcome to Nginx-Red!
        </h1>
      </body>
    </html>
